### ISSUE TITLE
Cannot read properties of undefined (reading 'pathPrefix')

### ISSUE THREAD

**Issue by dtcarls** [bramhoven/serverless-lambda-layer-packager#3]
After installing the plugin when running `serverless --help` it throws `Cannot read properties of undefined (reading 'pathPrefix')` error. I have added 
```
custom:
  serverless-lambda-layer-packager:
    pathPrefix: python/
    runtime: python3.8
```
to my serverless.yml. Error also occurs when trying to do a serverless deploy.
